MetaforSite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('metaphors.urls')),
    path('admin/', admin.site.urls),
]

handler404 = "metaphors.views.page_not_found_view"

metaphors/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views
from .views import ImageCreateView, ImageCreateViewEn

urlpatterns = [

    path('add/', ImageCreateView.as_view(), name='add_image'),
    path('add/en/', ImageCreateViewEn.as_view(), name='add_image_en'),
    path('en/', views.metaphors_get_en, name='home_en'),
    path('', views.metaphors_get, name='home'),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

metaphors/models.py
import os
import hashlib

from deep_translator.exceptions import ElementNotFoundInGetRequest
from django.db import models
from deep_translator import GoogleTranslator


def hash_upload(instance, filename):
    instance.image.open()  # make sure we're at the beginning of the file
    contents = instance.image.read()  # get the contents
    fname, ext = os.path.splitext(filename)
    return "{0}/{1}{2}".format('image/', hashlib.sha256(contents).hexdigest(), ext)  # assemble the filename
    # raise Exception('файл уже есть')


# Create your models here.


class Metaphors(models.Model):
    name = models.CharField(max_length=250, default=None)
    en_name = models.CharField(max_length=250, default=None)
    image = models.ImageField(upload_to=hash_upload)

    def __str__(self):
        return self.name

    '''
    method to validate files if file exists 
    '''

    def save(self, *args, **kwargs):
        '''
        try:
            hash_upload()
        except Exception:
            return
        '''
        if self.name is None:
            try:
                self.name = GoogleTranslator(source='english', target='russian').translate(self.en_name)
                super(Metaphors, self).save(*args, **kwargs)
            except ElementNotFoundInGetRequest:
                self.name = ''
                super(Metaphors, self).save(*args, **kwargs)

        if self.en_name is None:
            try:
                self.en_name = GoogleTranslator(source='russian', target='english').translate(self.name)
                super(Metaphors, self).save(*args, **kwargs)
            except ElementNotFoundInGetRequest:
                self.en_name = ''
                super(Metaphors, self).save(*args, **kwargs)

        else:
            super(Metaphors, self).save(*args, **kwargs)

metaphors/forms.py
from django import forms


class ContactForm(forms.Form):
    from_email = forms.EmailField(label='Email', required=True)

    message = forms.CharField(label='Сообщение', widget=forms.Textarea, required=True)

metaphors/views.py
from django.db.models import Q
from django.db.models.functions import Lower
from django.http import JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView

from .models import Metaphors


from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import ContactForm
from MetaforSite.settings import EMAIL_HOST_USER, EMAIL_GETTER


class ImageCreateView(CreateView):
    model = Metaphors
    fields = ('name', 'image')
    template_name = 'add_image.html'
    success_url = reverse_lazy('home')


class ImageCreateViewEn(CreateView):
    model = Metaphors
    fields = ('en_name', 'image')
    template_name = 'add_image_en.html'
    success_url = reverse_lazy('home_en')


def page_not_found_view(request, exception):
    return render(request, '404.html', status=404)


def metaphors_get(request):
    ctx = {}
    query = request.GET.get("image_query", "")
    if query:
        object_list = Metaphors.objects.filter(Q(name__icontains=query))[:15]

    else:
        object_list = Metaphors.objects.all()[:15]

    ctx["object_list"] = object_list
    print(ctx)
    if request.is_ajax():
        html = render_to_string(
            template_name='home_ajax.html',
            context={'object_list': object_list})

        data_dict = {"html_from_view": html}
        return JsonResponse(data=data_dict, safe=False)

    if request.method == 'GET':
        form = ContactForm()
    elif request.method == 'POST':
        # если метод POST, проверим форму и отправим письмо
        form = ContactForm(request.POST)
        if form.is_valid():

            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(f'Письмо с сайта метафор от {from_email}', message,
                          EMAIL_HOST_USER, [EMAIL_GETTER])
            except BadHeaderError:
                return HttpResponse('Ошибка в теме письма.')
            return redirect('/')
    else:
        return HttpResponse('Неверный запрос.')

    ctx['form'] = form

    return render(request, "home.html", context=ctx)


def metaphors_get_en(request):
    ctx_1 = {}
    query = request.GET.get("image_query", "")
    if query:
        object_list = Metaphors.objects.filter(Q(en_name__icontains=query))[:15]

    else:
        object_list = Metaphors.objects.all()[:15]

    ctx_1["object_list"] = object_list

    if request.is_ajax():
        html = render_to_string(
            template_name='home_ajax_en.html',
            context={'object_list': object_list})

        data_dict = {"html_from_view_1": html}
        return JsonResponse(data=data_dict, safe=False)

    if request.method == 'GET':
        form = ContactForm()
    elif request.method == 'POST':
        # если метод POST, проверим форму и отправим письмо
        form = ContactForm(request.POST)
        if form.is_valid():

            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(f'Письмо с сайта метафор от {from_email}', message,
                          EMAIL_HOST_USER, [EMAIL_GETTER])
            except BadHeaderError:
                return HttpResponse('Ошибка в теме письма.')
            return redirect('/en')
    else:
        return HttpResponse('Неверный запрос.')

    ctx_1['form'] = form

    return render(request, "home_en.html", context=ctx_1)

templates/add_image.html
{% load static %}


<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/metaphor.ico' %}?ver=2"/>
    <link href="{% static 'css/dist/styles.css' %}" rel="stylesheet"/>
    <title>Добавь свою метафору</title>
</head>





<!-- Section 1 -->
<body class="w-full px-8 py-16 bg-blue-100 xl:px-8 ">
    <div class="max-w-5xl mx-auto flex justify-center" >


            <div class="w-full mt-16 md:mt-0 md:w-2/5">
                <div class="relative z-10 h-auto p-8 py-10 overflow-hidden bg-white border-b-2 border-gray-300 rounded-lg shadow-2xl px-7">
                    <h3 class="mb-6 text-2xl font-medium text-center">Добавь свою метафору</h3>
                    {% block content %}
                      <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="text" name="name" class="block w-full px-4 py-3 mb-4 border border-2 border-transparent border-gray-200 rounded-lg focus:ring focus:ring-blue-500 focus:outline-none" placeholder='Название метафоры' maxlength="250" required="" id="id_name">
                        <input type="file" name="image" class="input-file absolute overflow-hidden" style="z-index: -1; width: 0.1px ; height: 0.1px; opacity: 0" data-multiple-caption="{count} file selected" required="" id="id_image">
                        <label style="display: block;cursor: pointer; background-color:blue; color:white; padding:15px 30px; margin-bottom:6px; text-align: center; border-radius: 0.5rem;" for="id_image"><span class="text-lg">Выберите файл</span></label>

                        <button type="submit" class="btn btn-success text-lg w-full px-3 py-4 font-medium text-white bg-blue-600 rounded-lg mt-4">Добавить метафору</button>
                      </form>
                    {% endblock %}

                    <p class="w-full mt-4 text-base text-center text-gray-500"><a href="/" class="text-blue-500 underline">Вернуться на главную страницу</a></p>
                </div>
            <div class="relative z-10 h-auto p-8 py-10 overflow-hidden bg-white border-b-2 border-gray-300 rounded-lg shadow-2xl px-7">
                <h1 class="text-2xl">Читай как быстро придумать нужную метафору</h1>
                <a href="https://medium.com/smysloteka/%D0%BA%D0%B0%D0%BA-%D0%BD%D0%B0%D1%80%D0%B8%D1%81%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%87%D1%82%D0%BE-%D1%83%D0%B3%D0%BE%D0%B4%D0%BD%D0%BE-%D1%80%D0%B8%D1%81%D1%83%D0%B5%D0%BC-%D0%BF%D0%BE-%D0%B0%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC%D1%83-%D1%80%D0%B5%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D0%B8-%D0%B0%D0%B1%D1%81%D1%82%D1%80%D0%B0%D0%BA%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D0%BE%D0%BD%D1%8F%D1%82%D0%B8%D1%8F-db713eca6344" ><button type="btn" class="mt-8 form-control btn btn-success rounded-lg py-3 bg-purple-500 text-center text-lg text-semibold text-white w-full">Читать</button></a>

            </div>

            </div>

        </div>

</body>


<script>
    const regex = /^[?@!,-_+$&%#^()*.а-яА-ЯёЁ0-9\s]+$/;
    function validate(e) {
      const chars = e.target.value.split('');
      const char = chars.pop();
      if (!regex.test(char)) {
        e.target.value = chars.join('');
        console.log(`${char} is not a valid character.`);
      }
    }
    document.querySelector('#id_name').addEventListener('input', validate);

    var inputs = document.querySelectorAll( '.input-file' );
Array.prototype.forEach.call( inputs, function( input )
{
	var label	 = input.nextElementSibling,
		labelVal = label.innerHTML;

	input.addEventListener( 'change', function( e )
	{
		var fileName = '';
		if( this.files && this.files.length > 1 )
			fileName = ( this.getAttribute( 'data-multiple-caption' ) || '' ).replace( '{count}', this.files.length );
		else
			fileName = e.target.value.split( '\\' ).pop();

		if( fileName )
			label.querySelector( 'span' ).innerHTML = fileName;
		else
			label.innerHTML = labelVal;
	});
});
</script>






</html>

templates/add_image_en.html
{% load static %}


<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/metaphor.ico' %}?ver=2"/>
    <link href="{% static 'css/dist/styles.css' %}" rel="stylesheet"/>
    <title>Add your metaphor</title>
</head>



<body class="w-full px-8 py-16 bg-blue-100 xl:px-8 ">
    <div class="max-w-5xl mx-auto flex justify-center" >


            <div class="w-full mt-16 md:mt-0 md:w-2/5">
                <div class="relative z-10 h-auto p-8 py-10 overflow-hidden bg-white border-b-2 border-gray-300 rounded-lg shadow-2xl px-7">
                    <h3 class="mb-6 text-2xl font-medium text-center">Add your metaphor</h3>
                     {% block content %}
                      <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="text" name="name" class="block w-full px-4 py-3 mb-4 border border-2 border-transparent border-gray-200 rounded-lg focus:ring focus:ring-blue-500 focus:outline-none" placeholder='The name of the metaphor' maxlength="250" required="" id="id_name">
                        <input type="file" name="image" class="input-file absolute overflow-hidden" style="z-index: -1; width: 0.1px ; height: 0.1px; opacity: 0" data-multiple-caption="{count} file selected" required="" id="id_image">
                        <label style="display: block;cursor: pointer; background-color:blue; color:white; padding:15px 30px; margin-bottom:6px; text-align: center; border-radius: 0.5rem;" for="id_image"><span class="text-lg">Add a metaphor</span></label>

                        <button type="submit" class="btn btn-success text-lg w-full px-3 py-4 font-medium text-white bg-blue-600 rounded-lg mt-4">Add a metaphor</button>
                      </form>
                    {% endblock %}

                    <p class="w-full mt-4 text-base text-center text-gray-500"><a href="/" class="text-blue-500 underline">Go back to the main page</a></p>
                </div>
            <div class="relative z-10 h-auto p-8 py-10 overflow-hidden bg-white border-b-2 border-gray-300 rounded-lg shadow-2xl px-7">
                <h1 class="text-2xl">Read how to quickly come up with the right metaphor</h1>
                <a href="https://medium.com/smysloteka/%D0%BA%D0%B0%D0%BA-%D0%BD%D0%B0%D1%80%D0%B8%D1%81%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%87%D1%82%D0%BE-%D1%83%D0%B3%D0%BE%D0%B4%D0%BD%D0%BE-%D1%80%D0%B8%D1%81%D1%83%D0%B5%D0%BC-%D0%BF%D0%BE-%D0%B0%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC%D1%83-%D1%80%D0%B5%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D0%B8-%D0%B0%D0%B1%D1%81%D1%82%D1%80%D0%B0%D0%BA%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D0%BE%D0%BD%D1%8F%D1%82%D0%B8%D1%8F-db713eca6344" ><button type="btn" class="mt-8 form-control btn btn-success rounded-lg py-3 bg-purple-500 text-center text-lg text-semibold text-white w-full">Read</button></a>

            </div>

            </div>

        </div>

</body>


<script>
    const regex = /^[?@!,-_+$&%#^()*.A-Za-z0-9\s]+$/;
    function validate(e) {
      const chars = e.target.value.split('');
      const char = chars.pop();
      if (!regex.test(char)) {
        e.target.value = chars.join('');
        console.log(`${char} is not a valid character.`);
      }
    }
    document.querySelector('#id_en_name').addEventListener('input', validate);

    var inputs = document.querySelectorAll( '.input-file' );
Array.prototype.forEach.call( inputs, function( input )
{
	var label	 = input.nextElementSibling,
		labelVal = label.innerHTML;

	input.addEventListener( 'change', function( e )
	{
		var fileName = '';
		if( this.files && this.files.length > 1 )
			fileName = ( this.getAttribute( 'data-multiple-caption' ) || '' ).replace( '{count}', this.files.length );
		else
			fileName = e.target.value.split( '\\' ).pop();

		if( fileName )
			label.querySelector( 'span' ).innerHTML = fileName;
		else
			label.innerHTML = labelVal;
	});
});
</script>






</html>

templates/home.html
{% load static %}


<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link href="{% static 'css/dist/styles.css' %}" rel="stylesheet"/>
    <link rel="shortcut icon" type="image/png" href="{% static 'img/metaphor.ico' %}?ver=2"/>

    <title>Найди свою метафору</title>
</head>


<body class="w-full px-3 antialiased bg-gradient-to-b from-indigo-500 to-blue-500 lg:px-6">


<!-- Section 1 -->

    <div class="w-full px-5 py-6 mx-auto space-y-5 sm:py-8 md:py-12 sm:space-y-8 md:space-y-16 max-w-7xl">
        <nav class="flex items-center w-full h-24 select-none" x-data="{ showMenu: false }">
            <div class="relative flex flex-wrap items-center justify-between w-full h-24 mx-auto font-medium md:justify-center">
                <a href="#_" class="w-1/4 py-4 pl-6 pr-4 md:pl-4 md:py-0">
                    <span class="p-1 text-2xl font-black leading-none text-white select-none"><span>FindMetaphor</span><span class="text-indigo-300">.</span></span>
                </a>
                <div class="fixed top-0 left-0 z-40 items-center hidden w-full h-full p-3 text-xl bg-gray-900 bg-opacity-50 md:text-sm lg:text-base md:w-3/4 md:bg-transparent md:p-0 md:relative md:flex" :class="{'flex': showMenu, 'hidden': !showMenu }">
                    <div class="flex-col w-full h-auto h-full overflow-hidden bg-white rounded-lg select-none md:bg-transparent md:rounded-none md:relative md:flex md:flex-row md:overflow-auto">
                        <div class="flex flex-col items-center justify-center w-full h-full mt-12 text-center text-indigo-700 md:text-indigo-200 md:w-2/3 md:mt-0 md:flex-row md:items-center">
                            <a href="#" class="inline-block px-4 py-2 mx-2 font-medium text-left  text-indigo-700 md:text-white md:px-0 lg:mx-3 md:text-center" data-anchor="anchor01">Найти</a>
                            <a href="#" class="inline-block px-0 px-4 py-2 mx-2 font-medium text-left md:px-0 hover:text-indigo-700 md:hover:text-white lg:mx-3 md:text-center" data-anchor="anchor02">Добавить</a>
                            <a href="#" class="inline-block px-0 px-4 py-2 mx-2 font-medium text-left md:px-0 hover:text-indigo-700 md:hover:text-white lg:mx-3 md:text-center" data-anchor="anchor03">Метафоры</a>
                            <a href="#" class="inline-block px-0 px-4 py-2 mx-2 font-medium text-left md:px-0 hover:text-indigo-700 md:hover:text-white lg:mx-3 md:text-center" data-anchor="anchor04">Есть вопросы</a>
                        </div>
                        <div class="flex flex-col items-center justify-end w-full h-full pt-4 md:w-1/3 md:flex-row md:py-0">
                            <a href="/en" class="w-full pl-6 mr-0 text-white hover:text-white md:pl-0 md:mr-3 lg:mr-5 md:w-auto">English</a>
                            <a href="/" class="inline-flex items-center justify-center px-4 py-2 mr-1 text-base font-medium leading-6 text-indigo-600 whitespace-no-wrap transition duration-150 ease-in-out bg-white border border-transparent rounded-full hover:bg-white focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700">Russian</a>
                        </div>
                    </div>
                </div>
                <div @click="showMenu = !showMenu" class="absolute right-0 z-50 flex flex-col items-end w-10 h-10 p-2 mr-4 rounded-full cursor-pointer md:hidden hover:bg-gray-900 hover:bg-opacity-10" :class="{ 'text-gray-400': showMenu, 'text-gray-100': !showMenu }">
                    <svg class="w-6 h-6" x-show="!showMenu" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor" x-cloak="">
                        <path d="M4 6h16M4 12h16M4 18h16"></path>
                    </svg>
                    <svg class="w-6 h-6" x-show="showMenu" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" x-cloak="">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
                    </svg>
                </div>
            </div>
        </nav>
        <div class="container py-16 mx-auto text-center sm:px-4">

            <h1 id="anchor01" class="text-5xl font-extrabold leading-10 tracking-tight text-white sm:text-5xl sm:leading-none md:text-6xl xl:text-7xl"><span class="block">Найди свою метафору.</span><span class="block">Вы можете найти визуальную метафору для передачи нужного вам смысла</span></h1>

            <div class="text-2xl max-w-xl mx-auto mt-6 text-center font-medium text-white md:mt-12">Введите в строку поиска нужное вам понятие, фразу или выражение из нескольких фраз</div>
            <form action="{% url 'home' %}" method="get">
                <div class=" relative flex items-center max-w-md mx-auto mt-4 overflow-hidden text-center rounded-full">

                    <input id="user-input" name="image_query" type="text" placeholder="Найти метафору" class="w-full h-12 px-6 py-2 font-medium text-indigo-800 focus:outline-none">
                    <button type="submit" class="inline-flex items-center w-32 h-12 px-8 text-base font-bold leading-6 text-white transition duration-150 ease-in-out bg-indigo-400 border border-transparent hover:bg-indigo-700 focus:outline-none active:bg-indigo-700">Найти</button>
                </div>
            </form>
            <div class="mt-4 text-xl text-medium text-white">Например: идея, ветер </div>

            </div>
        <span id="anchor02" class="text-center text-white mt-6"><span class="block text-5xl font-extrabold">Помогите наполнить севрис.</span><span class="block text-5xl font-extrabold"> Загрузите свою картинку метафоры и название, смысл которого она передаёт</span><a href="https://medium.com/smysloteka/%D0%BA%D0%B0%D0%BA-%D0%BD%D0%B0%D1%80%D0%B8%D1%81%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%87%D1%82%D0%BE-%D1%83%D0%B3%D0%BE%D0%B4%D0%BD%D0%BE-%D1%80%D0%B8%D1%81%D1%83%D0%B5%D0%BC-%D0%BF%D0%BE-%D0%B0%D0%BB%D0%B3%D0%BE%D1%80%D0%B8%D1%82%D0%BC%D1%83-%D1%80%D0%B5%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D0%B8-%D0%B0%D0%B1%D1%81%D1%82%D1%80%D0%B0%D0%BA%D1%82%D0%BD%D1%8B%D0%B5-%D0%BF%D0%BE%D0%BD%D1%8F%D1%82%D0%B8%D1%8F-db713eca6344"><span class="text-2xl font-semibold block underline m-8 hover:text-blue-300">Читай как быстро придумать нужную метафору</span></a></span>
            <a href="/add/"><button type="submit" class="btn btn-success px-20 py-4 md-3 font-bold text-white bg-blue-600 rounded-lg relativeЯ flex items-center max-w-md mx-auto text-center text-2xl"><svg xmlns="http://www.w3.org/2000/svg" height="40px" viewBox="0 0 24 24" width="40px" fill="white"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z"/></svg>Добавить свою метафору</button></a>


                {% include 'home_ajax.html' %}


          <div class="mt-8 py-20 sm:mx-auto sm:w-full sm:max-w-md">
            <div id="anchor04" class="bg-white py-8 px-6 shadow rounded-lg sm:px-10">
              <h1 class="text-2xl">Если есть вопросы по сервису и сайту, задайте их</h1>
              <form class="mb-0 space-y-6 " method="post">
                {% csrf_token %}
                <div>
                    <label for="id_from_email">Почта:</label> <input type="email" name="from_email" placeholder="example@example.com" class="w-full rounded-lg border border-gray-300 px-3 py-2" required id="id_from_email">
                </div>

                <div>
                <label for="id_message">Сообщение:</label> <textarea name="message" class="w-full border rounded-lg border-gray-300 px-3 py-2" cols="40" rows="10" required id="id_message"></textarea>
                </div>

                <div class="form-actions form-group ">
                  <button type="submit" class="form-control btn btn-success rounded-lg py-3 bg-indigo-500 text-center text-lg text-white w-full">Отправить</button>
                </div>
              </form>
            </div>
          </div>

</div>






</body>

{% block javascript %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


<script>

const user_input = $("#user-input")
const artists_div = $('#replaceable-content')
const endpoint = ''
const delay_by_in_ms = 700
let scheduled_function = false

let ajax_call = function (endpoint, request_parameters) {
    $.getJSON(endpoint, request_parameters)
        .done(response => {
            // fade out the artists_div, then:
            artists_div.fadeTo('slow', 0).promise().then(() => {
                // replace the HTML contents
                artists_div.html(response['html_from_view'])

                // fade-in the div with new contents
                artists_div.fadeTo('slow', 1)

            })
        })
}


user_input.on('keyup', function () {
    const request_parameters = {
        image_query: $(this).val() // value of user_input: the HTML element with ID user-input
    }




    // if scheduled_function is NOT false, cancel the execution of the function
    if (scheduled_function) {
        clearTimeout(scheduled_function)
    }

    // setTimeout returns the ID of the function to be executed
    scheduled_function = setTimeout(ajax_call, delay_by_in_ms, endpoint, request_parameters)
})

$('[data-anchor]').on('click', function(){
  let id = $(this).attr('data-anchor');
  if($(document).find('#'+id).length > 0) {
    let posY = $(document).find('#'+id).position().top;
    $('html,body').animate({
      scrollTop: posY
    }, 1000);
  }
  return false;
});

$(function(){
  $('.minimized').click(function(event) {
    var i_path = $(this).attr('src');
    $('body').append('<div id="overlay"></div><div id="magnify"><img src="'+i_path+'"><div id="close-popup"><i></i></div></div>');
    $('#magnify').css({
     left: ($(document).width() - $('#magnify').outerWidth())/2,
     // top: ($(document).height() - $('#magnify').outerHeight())/2 upd: 24.10.2016
            top: ($(window).height() - $('#magnify').outerHeight())/2
   });
    $('#overlay, #magnify').fadeIn('fast');
  });

  $('body').on('click', '#close-popup, #overlay', function(event) {
    event.preventDefault();
    $('#overlay, #magnify').fadeOut('fast', function() {
      $('#close-popup, #magnify, #overlay').remove();
    });
  });
});


</script>
{% endblock javascript %}
</html>

templates/home_ajax.html
{% if object_list %}
                    <div id="replaceable-content">
                        <div id="anchor03" class="flex grid grid-cols-12 pb-10 sm:px-5 gap-x-8 gap-y-16" >
                        {% for metaphors in object_list %}
                                    {% if metaphors.name %}
                                    <div class="flex flex-col items-center col-span-12 space-y-3 sm:col-span-6 xl:col-span-4 bg-white rounded-lg">

                                            <img class="minimized object-cover w-full md:w-full overflow-hidden rounded-t-lg shadow h-56 " src="{{ metaphors.image.url}}" alt="{{ metaphors.name}}">


                                        <h2 class="text-lg font-semibold sm:text-xl md:text-2xl pb-2 text-purple-900">{{ metaphors.name }}</h2>

                                    </div>
                                    {% endif %}
                        {% endfor %}
                        </div>
                    </div>
{% else %}
    <div id="anchor03" class="max-w-lg mx-auto mt-6 text-sm text-center text-indigo-100 md:mt-12 sm:text-base md:max-w-xl md:text-lg xl:text-xl">Метафор с таким именем не найдено. Попробуйте ввести другое название</div>

{% endif %}

templates/home_ajax_en.html
{% if object_list %}
                    <div id="replaceable-content">
                        <div id="anchor03" class="flex grid grid-cols-12 pb-10 sm:px-5 gap-x-10 gap-y-12" >
                        {% for metaphors in object_list %}
                                    {% if metaphors.en_name %}
                                    <div class="flex flex-col items-center col-span-12 space-y-3 sm:col-span-6 xl:col-span-4 rounded-lg bg-white">

                                            <img class="minimized object-cover w-full md:w-full overflow-hidden rounded-t-lg shadow h-56" src="{{ metaphors.image.url}}" alt="{{ metaphors.en_name}}">


                                        <h2 class="text-lg font-semibold sm:text-xl md:text-2xl pb-2 text-purple-900">{{ metaphors.en_name }}</h2>

                                    </div>
                                    {% endif %}
                        {% endfor %}
                        </div>
                    </div>
{% else %}
    <div id="anchor03" class="max-w-lg mx-auto mt-6 text-sm text-center text-indigo-100 md:mt-12 sm:text-base md:max-w-xl md:text-lg xl:text-xl">No metaphors with this name were found. Try entering a different name</div>

{% endif %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-grey-lightest font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>